version: '2'
services:
  postgres:
    container_name: banco
    build: ./postgres
    image: sessionbeans/banco
    ports:
     - "5433:5432"
  web:
    container_name: app
    build: ./app
    image: sessionbeans/webapp
    ports: 
     - "8081:8080"
    links: 
     - "postgres:host-banco"
